### ISSUE TITLE
Only current context listed in context

### ISSUE THREAD

**Issue by yi-bai** [it2911/kubectl-cfg#11]
Even multiple contexts exist in .kubeconfig, only the current selected one is listed.

Steps to reproduce:
```
$ kubectl cfg add context c1
Context "c1" created.
$ kubectl cfg add context c2
Context "c2" created.
$ kubectl cfg add context c3
Context "c3" created.
$ kubectl cfg list context
CURRENT   CONTEXT_NAME     CLUSTER_NAME   AUTH_INFO          DEFAULT_NAMESPACE
*         k8s_playground   kubernetes     kubernetes-admin
```

Even `.kubeconfig` got manually updated this problem remains.

**Comment by it2911** [comment]
@yi-bai 

Thank you for reporting. This bug is solved in v0.1.0 version.
Please confirm it and close this issue.
