### ISSUE TITLE
Highlight 会错行

### ISSUE THREAD

**Issue by it2911** [it2911/kubectl-cfg#4]
使用highlight的时候，会发生错行的情况。

```
$ kubectl cfg list context                      
CURRENT   CONTEXT_NAME                  CLUSTER_NAME   AUTH_INFO          DEFAULT_NAMESPACE
*    kubernetes-admin@kubernetes   kubernetes     kubernetes-admin  
```

**Comment by vinci7** [comment]
Fixed by commit 
https://github.com/it2911/kubectl-cfg/commit/1077bb9fb8b40b11efb048d32f075561a6bf7c9e

**Comment by vinci7** [comment]
add highlight in all subcommand of list
https://github.com/it2911/kubectl-cfg/commit/4f43617c97ad14867c8f7e405bd78b3aead5b317
